/* libluxafor.h generated by valac 0.30.1, the Vala compiler, do not modify */


#ifndef __LIBLUXAFOR_H__
#define __LIBLUXAFOR_H__

#include <glib.h>
#include <glib-object.h>
#include <libusb.h>

G_BEGIN_DECLS


#define LUXAFOR_TYPE_LUXAFOR (luxafor_luxafor_get_type ())
#define LUXAFOR_LUXAFOR(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), LUXAFOR_TYPE_LUXAFOR, LuxaforLuxafor))
#define LUXAFOR_LUXAFOR_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), LUXAFOR_TYPE_LUXAFOR, LuxaforLuxaforClass))
#define LUXAFOR_IS_LUXAFOR(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), LUXAFOR_TYPE_LUXAFOR))
#define LUXAFOR_IS_LUXAFOR_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), LUXAFOR_TYPE_LUXAFOR))
#define LUXAFOR_LUXAFOR_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), LUXAFOR_TYPE_LUXAFOR, LuxaforLuxaforClass))

typedef struct _LuxaforLuxafor LuxaforLuxafor;
typedef struct _LuxaforLuxaforClass LuxaforLuxaforClass;
typedef struct _LuxaforLuxaforPrivate LuxaforLuxaforPrivate;

#define LUXAFOR_EFFECT_TYPE_EFFECT (luxafor_effect_effect_get_type ())
#define LUXAFOR_EFFECT_EFFECT(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), LUXAFOR_EFFECT_TYPE_EFFECT, LuxaforEffectEffect))
#define LUXAFOR_EFFECT_IS_EFFECT(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), LUXAFOR_EFFECT_TYPE_EFFECT))
#define LUXAFOR_EFFECT_EFFECT_GET_INTERFACE(obj) (G_TYPE_INSTANCE_GET_INTERFACE ((obj), LUXAFOR_EFFECT_TYPE_EFFECT, LuxaforEffectEffectIface))

typedef struct _LuxaforEffectEffect LuxaforEffectEffect;
typedef struct _LuxaforEffectEffectIface LuxaforEffectEffectIface;

#define LUXAFOR_DEVICE_TYPE_USB_DEVICE_FINDER (luxafor_device_usb_device_finder_get_type ())
#define LUXAFOR_DEVICE_USB_DEVICE_FINDER(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), LUXAFOR_DEVICE_TYPE_USB_DEVICE_FINDER, LuxaforDeviceUsbDeviceFinder))
#define LUXAFOR_DEVICE_IS_USB_DEVICE_FINDER(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), LUXAFOR_DEVICE_TYPE_USB_DEVICE_FINDER))
#define LUXAFOR_DEVICE_USB_DEVICE_FINDER_GET_INTERFACE(obj) (G_TYPE_INSTANCE_GET_INTERFACE ((obj), LUXAFOR_DEVICE_TYPE_USB_DEVICE_FINDER, LuxaforDeviceUsbDeviceFinderIface))

typedef struct _LuxaforDeviceUsbDeviceFinder LuxaforDeviceUsbDeviceFinder;
typedef struct _LuxaforDeviceUsbDeviceFinderIface LuxaforDeviceUsbDeviceFinderIface;

#define LUXAFOR_DEVICE_TYPE_LUXAFOR_FINDER (luxafor_device_luxafor_finder_get_type ())
#define LUXAFOR_DEVICE_LUXAFOR_FINDER(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), LUXAFOR_DEVICE_TYPE_LUXAFOR_FINDER, LuxaforDeviceLuxaforFinder))
#define LUXAFOR_DEVICE_LUXAFOR_FINDER_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), LUXAFOR_DEVICE_TYPE_LUXAFOR_FINDER, LuxaforDeviceLuxaforFinderClass))
#define LUXAFOR_DEVICE_IS_LUXAFOR_FINDER(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), LUXAFOR_DEVICE_TYPE_LUXAFOR_FINDER))
#define LUXAFOR_DEVICE_IS_LUXAFOR_FINDER_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), LUXAFOR_DEVICE_TYPE_LUXAFOR_FINDER))
#define LUXAFOR_DEVICE_LUXAFOR_FINDER_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), LUXAFOR_DEVICE_TYPE_LUXAFOR_FINDER, LuxaforDeviceLuxaforFinderClass))

typedef struct _LuxaforDeviceLuxaforFinder LuxaforDeviceLuxaforFinder;
typedef struct _LuxaforDeviceLuxaforFinderClass LuxaforDeviceLuxaforFinderClass;
typedef struct _LuxaforDeviceLuxaforFinderPrivate LuxaforDeviceLuxaforFinderPrivate;

#define LUXAFOR_EFFECT_TYPE_COLOR (luxafor_effect_color_get_type ())
#define LUXAFOR_EFFECT_COLOR(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), LUXAFOR_EFFECT_TYPE_COLOR, LuxaforEffectColor))
#define LUXAFOR_EFFECT_COLOR_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), LUXAFOR_EFFECT_TYPE_COLOR, LuxaforEffectColorClass))
#define LUXAFOR_EFFECT_IS_COLOR(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), LUXAFOR_EFFECT_TYPE_COLOR))
#define LUXAFOR_EFFECT_IS_COLOR_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), LUXAFOR_EFFECT_TYPE_COLOR))
#define LUXAFOR_EFFECT_COLOR_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), LUXAFOR_EFFECT_TYPE_COLOR, LuxaforEffectColorClass))

typedef struct _LuxaforEffectColor LuxaforEffectColor;
typedef struct _LuxaforEffectColorClass LuxaforEffectColorClass;
typedef struct _LuxaforEffectColorPrivate LuxaforEffectColorPrivate;

#define LUXAFOR_EFFECT_TYPE_SHUTDOWN (luxafor_effect_shutdown_get_type ())
#define LUXAFOR_EFFECT_SHUTDOWN(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), LUXAFOR_EFFECT_TYPE_SHUTDOWN, LuxaforEffectShutdown))
#define LUXAFOR_EFFECT_SHUTDOWN_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), LUXAFOR_EFFECT_TYPE_SHUTDOWN, LuxaforEffectShutdownClass))
#define LUXAFOR_EFFECT_IS_SHUTDOWN(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), LUXAFOR_EFFECT_TYPE_SHUTDOWN))
#define LUXAFOR_EFFECT_IS_SHUTDOWN_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), LUXAFOR_EFFECT_TYPE_SHUTDOWN))
#define LUXAFOR_EFFECT_SHUTDOWN_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), LUXAFOR_EFFECT_TYPE_SHUTDOWN, LuxaforEffectShutdownClass))

typedef struct _LuxaforEffectShutdown LuxaforEffectShutdown;
typedef struct _LuxaforEffectShutdownClass LuxaforEffectShutdownClass;
typedef struct _LuxaforEffectShutdownPrivate LuxaforEffectShutdownPrivate;

struct _LuxaforLuxafor {
	GTypeInstance parent_instance;
	volatile int ref_count;
	LuxaforLuxaforPrivate * priv;
};

struct _LuxaforLuxaforClass {
	GTypeClass parent_class;
	void (*finalize) (LuxaforLuxafor *self);
};

struct _LuxaforEffectEffectIface {
	GTypeInterface parent_iface;
	void (*handle) (LuxaforEffectEffect* self, LuxaforLuxafor* luxafor);
};

struct _LuxaforDeviceUsbDeviceFinderIface {
	GTypeInterface parent_iface;
	libusb_device* (*find) (LuxaforDeviceUsbDeviceFinder* self);
};

struct _LuxaforDeviceLuxaforFinder {
	GObject parent_instance;
	LuxaforDeviceLuxaforFinderPrivate * priv;
};

struct _LuxaforDeviceLuxaforFinderClass {
	GObjectClass parent_class;
};

struct _LuxaforEffectColor {
	GTypeInstance parent_instance;
	volatile int ref_count;
	LuxaforEffectColorPrivate * priv;
	guint8 intensity;
	guint8 red;
	guint8 green;
	guint8 blue;
};

struct _LuxaforEffectColorClass {
	GTypeClass parent_class;
	void (*finalize) (LuxaforEffectColor *self);
};

struct _LuxaforEffectShutdown {
	GTypeInstance parent_instance;
	volatile int ref_count;
	LuxaforEffectShutdownPrivate * priv;
};

struct _LuxaforEffectShutdownClass {
	GTypeClass parent_class;
	void (*finalize) (LuxaforEffectShutdown *self);
};


gpointer luxafor_luxafor_ref (gpointer instance);
void luxafor_luxafor_unref (gpointer instance);
GParamSpec* luxafor_param_spec_luxafor (const gchar* name, const gchar* nick, const gchar* blurb, GType object_type, GParamFlags flags);
void luxafor_value_set_luxafor (GValue* value, gpointer v_object);
void luxafor_value_take_luxafor (GValue* value, gpointer v_object);
gpointer luxafor_value_get_luxafor (const GValue* value);
GType luxafor_luxafor_get_type (void) G_GNUC_CONST;
LuxaforLuxafor* luxafor_luxafor_new (libusb_context* context);
LuxaforLuxafor* luxafor_luxafor_construct (GType object_type, libusb_context* context);
void luxafor_luxafor_close (LuxaforLuxafor* self);
void luxafor_luxafor_write (LuxaforLuxafor* self, guint8* data, int data_length1);
GType luxafor_effect_effect_get_type (void) G_GNUC_CONST;
void luxafor_luxafor_send (LuxaforLuxafor* self, LuxaforEffectEffect* effect);
GType luxafor_device_usb_device_finder_get_type (void) G_GNUC_CONST;
libusb_device* luxafor_device_usb_device_finder_find (LuxaforDeviceUsbDeviceFinder* self);
GType luxafor_device_luxafor_finder_get_type (void) G_GNUC_CONST;
LuxaforDeviceLuxaforFinder* luxafor_device_luxafor_finder_new (libusb_context* context);
LuxaforDeviceLuxaforFinder* luxafor_device_luxafor_finder_construct (GType object_type, libusb_context* context);
void luxafor_effect_effect_handle (LuxaforEffectEffect* self, LuxaforLuxafor* luxafor);
gpointer luxafor_effect_color_ref (gpointer instance);
void luxafor_effect_color_unref (gpointer instance);
GParamSpec* luxafor_effect_param_spec_color (const gchar* name, const gchar* nick, const gchar* blurb, GType object_type, GParamFlags flags);
void luxafor_effect_value_set_color (GValue* value, gpointer v_object);
void luxafor_effect_value_take_color (GValue* value, gpointer v_object);
gpointer luxafor_effect_value_get_color (const GValue* value);
GType luxafor_effect_color_get_type (void) G_GNUC_CONST;
LuxaforEffectColor* luxafor_effect_color_new (guint8 intensity, guint8 red, guint8 green, guint8 blue);
LuxaforEffectColor* luxafor_effect_color_construct (GType object_type, guint8 intensity, guint8 red, guint8 green, guint8 blue);
gpointer luxafor_effect_shutdown_ref (gpointer instance);
void luxafor_effect_shutdown_unref (gpointer instance);
GParamSpec* luxafor_effect_param_spec_shutdown (const gchar* name, const gchar* nick, const gchar* blurb, GType object_type, GParamFlags flags);
void luxafor_effect_value_set_shutdown (GValue* value, gpointer v_object);
void luxafor_effect_value_take_shutdown (GValue* value, gpointer v_object);
gpointer luxafor_effect_value_get_shutdown (const GValue* value);
GType luxafor_effect_shutdown_get_type (void) G_GNUC_CONST;
LuxaforEffectShutdown* luxafor_effect_shutdown_new (void);
LuxaforEffectShutdown* luxafor_effect_shutdown_construct (GType object_type);


G_END_DECLS

#endif
