/* libluxafor.h generated by valac 0.30.1, the Vala compiler, do not modify */


#ifndef __LIBLUXAFOR_H__
#define __LIBLUXAFOR_H__

#include <glib.h>
#include <glib-object.h>
#include <libusb.h>

G_BEGIN_DECLS


#define LUXAFOR_TYPE_LUXAFOR (luxafor_luxafor_get_type ())
#define LUXAFOR_LUXAFOR(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), LUXAFOR_TYPE_LUXAFOR, LuxaforLuxafor))
#define LUXAFOR_LUXAFOR_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), LUXAFOR_TYPE_LUXAFOR, LuxaforLuxaforClass))
#define LUXAFOR_IS_LUXAFOR(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), LUXAFOR_TYPE_LUXAFOR))
#define LUXAFOR_IS_LUXAFOR_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), LUXAFOR_TYPE_LUXAFOR))
#define LUXAFOR_LUXAFOR_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), LUXAFOR_TYPE_LUXAFOR, LuxaforLuxaforClass))

typedef struct _LuxaforLuxafor LuxaforLuxafor;
typedef struct _LuxaforLuxaforClass LuxaforLuxaforClass;
typedef struct _LuxaforLuxaforPrivate LuxaforLuxaforPrivate;

#define LUXAFOR_EFFECT_TYPE_EFFECT (luxafor_effect_effect_get_type ())
#define LUXAFOR_EFFECT_EFFECT(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), LUXAFOR_EFFECT_TYPE_EFFECT, LuxaforEffectEffect))
#define LUXAFOR_EFFECT_IS_EFFECT(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), LUXAFOR_EFFECT_TYPE_EFFECT))
#define LUXAFOR_EFFECT_EFFECT_GET_INTERFACE(obj) (G_TYPE_INSTANCE_GET_INTERFACE ((obj), LUXAFOR_EFFECT_TYPE_EFFECT, LuxaforEffectEffectIface))

typedef struct _LuxaforEffectEffect LuxaforEffectEffect;
typedef struct _LuxaforEffectEffectIface LuxaforEffectEffectIface;

#define LUXAFOR_DEVICE_TYPE_USB_DEVICE_FINDER (luxafor_device_usb_device_finder_get_type ())
#define LUXAFOR_DEVICE_USB_DEVICE_FINDER(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), LUXAFOR_DEVICE_TYPE_USB_DEVICE_FINDER, LuxaforDeviceUsbDeviceFinder))
#define LUXAFOR_DEVICE_IS_USB_DEVICE_FINDER(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), LUXAFOR_DEVICE_TYPE_USB_DEVICE_FINDER))
#define LUXAFOR_DEVICE_USB_DEVICE_FINDER_GET_INTERFACE(obj) (G_TYPE_INSTANCE_GET_INTERFACE ((obj), LUXAFOR_DEVICE_TYPE_USB_DEVICE_FINDER, LuxaforDeviceUsbDeviceFinderIface))

typedef struct _LuxaforDeviceUsbDeviceFinder LuxaforDeviceUsbDeviceFinder;
typedef struct _LuxaforDeviceUsbDeviceFinderIface LuxaforDeviceUsbDeviceFinderIface;

#define LUXAFOR_DEVICE_TYPE_LUXAFOR_FINDER (luxafor_device_luxafor_finder_get_type ())
#define LUXAFOR_DEVICE_LUXAFOR_FINDER(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), LUXAFOR_DEVICE_TYPE_LUXAFOR_FINDER, LuxaforDeviceLuxaforFinder))
#define LUXAFOR_DEVICE_LUXAFOR_FINDER_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), LUXAFOR_DEVICE_TYPE_LUXAFOR_FINDER, LuxaforDeviceLuxaforFinderClass))
#define LUXAFOR_DEVICE_IS_LUXAFOR_FINDER(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), LUXAFOR_DEVICE_TYPE_LUXAFOR_FINDER))
#define LUXAFOR_DEVICE_IS_LUXAFOR_FINDER_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), LUXAFOR_DEVICE_TYPE_LUXAFOR_FINDER))
#define LUXAFOR_DEVICE_LUXAFOR_FINDER_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), LUXAFOR_DEVICE_TYPE_LUXAFOR_FINDER, LuxaforDeviceLuxaforFinderClass))

typedef struct _LuxaforDeviceLuxaforFinder LuxaforDeviceLuxaforFinder;
typedef struct _LuxaforDeviceLuxaforFinderClass LuxaforDeviceLuxaforFinderClass;
typedef struct _LuxaforDeviceLuxaforFinderPrivate LuxaforDeviceLuxaforFinderPrivate;

#define LUXAFOR_EFFECT_TYPE_RAW (luxafor_effect_raw_get_type ())
#define LUXAFOR_EFFECT_RAW(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), LUXAFOR_EFFECT_TYPE_RAW, LuxaforEffectRaw))
#define LUXAFOR_EFFECT_RAW_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), LUXAFOR_EFFECT_TYPE_RAW, LuxaforEffectRawClass))
#define LUXAFOR_EFFECT_IS_RAW(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), LUXAFOR_EFFECT_TYPE_RAW))
#define LUXAFOR_EFFECT_IS_RAW_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), LUXAFOR_EFFECT_TYPE_RAW))
#define LUXAFOR_EFFECT_RAW_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), LUXAFOR_EFFECT_TYPE_RAW, LuxaforEffectRawClass))

typedef struct _LuxaforEffectRaw LuxaforEffectRaw;
typedef struct _LuxaforEffectRawClass LuxaforEffectRawClass;
typedef struct _LuxaforEffectRawPrivate LuxaforEffectRawPrivate;

#define LUXAFOR_EFFECT_TYPE_FADE_TO (luxafor_effect_fade_to_get_type ())
#define LUXAFOR_EFFECT_FADE_TO(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), LUXAFOR_EFFECT_TYPE_FADE_TO, LuxaforEffectFadeTo))
#define LUXAFOR_EFFECT_FADE_TO_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), LUXAFOR_EFFECT_TYPE_FADE_TO, LuxaforEffectFadeToClass))
#define LUXAFOR_EFFECT_IS_FADE_TO(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), LUXAFOR_EFFECT_TYPE_FADE_TO))
#define LUXAFOR_EFFECT_IS_FADE_TO_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), LUXAFOR_EFFECT_TYPE_FADE_TO))
#define LUXAFOR_EFFECT_FADE_TO_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), LUXAFOR_EFFECT_TYPE_FADE_TO, LuxaforEffectFadeToClass))

typedef struct _LuxaforEffectFadeTo LuxaforEffectFadeTo;
typedef struct _LuxaforEffectFadeToClass LuxaforEffectFadeToClass;
typedef struct _LuxaforEffectFadeToPrivate LuxaforEffectFadeToPrivate;

#define LUXAFOR_EFFECT_TYPE_COLOR (luxafor_effect_color_get_type ())
#define LUXAFOR_EFFECT_COLOR(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), LUXAFOR_EFFECT_TYPE_COLOR, LuxaforEffectColor))
#define LUXAFOR_EFFECT_COLOR_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), LUXAFOR_EFFECT_TYPE_COLOR, LuxaforEffectColorClass))
#define LUXAFOR_EFFECT_IS_COLOR(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), LUXAFOR_EFFECT_TYPE_COLOR))
#define LUXAFOR_EFFECT_IS_COLOR_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), LUXAFOR_EFFECT_TYPE_COLOR))
#define LUXAFOR_EFFECT_COLOR_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), LUXAFOR_EFFECT_TYPE_COLOR, LuxaforEffectColorClass))

typedef struct _LuxaforEffectColor LuxaforEffectColor;
typedef struct _LuxaforEffectColorClass LuxaforEffectColorClass;
typedef struct _LuxaforEffectColorPrivate LuxaforEffectColorPrivate;

#define LUXAFOR_EFFECT_TYPE_SHUTDOWN (luxafor_effect_shutdown_get_type ())
#define LUXAFOR_EFFECT_SHUTDOWN(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), LUXAFOR_EFFECT_TYPE_SHUTDOWN, LuxaforEffectShutdown))
#define LUXAFOR_EFFECT_SHUTDOWN_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), LUXAFOR_EFFECT_TYPE_SHUTDOWN, LuxaforEffectShutdownClass))
#define LUXAFOR_EFFECT_IS_SHUTDOWN(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), LUXAFOR_EFFECT_TYPE_SHUTDOWN))
#define LUXAFOR_EFFECT_IS_SHUTDOWN_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), LUXAFOR_EFFECT_TYPE_SHUTDOWN))
#define LUXAFOR_EFFECT_SHUTDOWN_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), LUXAFOR_EFFECT_TYPE_SHUTDOWN, LuxaforEffectShutdownClass))

typedef struct _LuxaforEffectShutdown LuxaforEffectShutdown;
typedef struct _LuxaforEffectShutdownClass LuxaforEffectShutdownClass;
typedef struct _LuxaforEffectShutdownPrivate LuxaforEffectShutdownPrivate;

#define LUXAFOR_EFFECT_TYPE_RANDOM_COLOR (luxafor_effect_random_color_get_type ())
#define LUXAFOR_EFFECT_RANDOM_COLOR(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), LUXAFOR_EFFECT_TYPE_RANDOM_COLOR, LuxaforEffectRandomColor))
#define LUXAFOR_EFFECT_RANDOM_COLOR_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), LUXAFOR_EFFECT_TYPE_RANDOM_COLOR, LuxaforEffectRandomColorClass))
#define LUXAFOR_EFFECT_IS_RANDOM_COLOR(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), LUXAFOR_EFFECT_TYPE_RANDOM_COLOR))
#define LUXAFOR_EFFECT_IS_RANDOM_COLOR_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), LUXAFOR_EFFECT_TYPE_RANDOM_COLOR))
#define LUXAFOR_EFFECT_RANDOM_COLOR_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), LUXAFOR_EFFECT_TYPE_RANDOM_COLOR, LuxaforEffectRandomColorClass))

typedef struct _LuxaforEffectRandomColor LuxaforEffectRandomColor;
typedef struct _LuxaforEffectRandomColorClass LuxaforEffectRandomColorClass;
typedef struct _LuxaforEffectRandomColorPrivate LuxaforEffectRandomColorPrivate;

typedef enum  {
	LUXAFOR_ERROR_ERR_DEVICE_LOOKUP,
	LUXAFOR_ERROR_ERR_DEVICE_COM
} LuxaforError;
#define LUXAFOR_ERROR luxafor_error_quark ()
struct _LuxaforLuxafor {
	GTypeInstance parent_instance;
	volatile int ref_count;
	LuxaforLuxaforPrivate * priv;
};

struct _LuxaforLuxaforClass {
	GTypeClass parent_class;
	void (*finalize) (LuxaforLuxafor *self);
};

typedef enum  {
	DEVICE_ERROR_DEVICE_NOT_FOUND,
	DEVICE_ERROR_ERROR_GET_DEVICE_HANDLE,
	DEVICE_ERROR_WRITE_ERROR
} DeviceError;
#define DEVICE_ERROR device_error_quark ()
typedef enum  {
	EFFECT_ERROR_WRITE_ERROR
} EffectError;
#define EFFECT_ERROR effect_error_quark ()
struct _LuxaforEffectEffectIface {
	GTypeInterface parent_iface;
	void (*handle) (LuxaforEffectEffect* self, LuxaforLuxafor* luxafor, GError** error);
};

struct _LuxaforDeviceUsbDeviceFinderIface {
	GTypeInterface parent_iface;
	libusb_device* (*find) (LuxaforDeviceUsbDeviceFinder* self, GError** error);
};

struct _LuxaforDeviceLuxaforFinder {
	GObject parent_instance;
	LuxaforDeviceLuxaforFinderPrivate * priv;
};

struct _LuxaforDeviceLuxaforFinderClass {
	GObjectClass parent_class;
};

struct _LuxaforEffectRaw {
	GObject parent_instance;
	LuxaforEffectRawPrivate * priv;
	guint8* bytes;
	gint bytes_length1;
	guint8 green;
	guint8 blue;
};

struct _LuxaforEffectRawClass {
	GObjectClass parent_class;
};

struct _LuxaforEffectFadeTo {
	GObject parent_instance;
	LuxaforEffectFadeToPrivate * priv;
};

struct _LuxaforEffectFadeToClass {
	GObjectClass parent_class;
};

struct _LuxaforEffectColor {
	GObject parent_instance;
	LuxaforEffectColorPrivate * priv;
};

struct _LuxaforEffectColorClass {
	GObjectClass parent_class;
};

struct _LuxaforEffectShutdown {
	GObject parent_instance;
	LuxaforEffectShutdownPrivate * priv;
};

struct _LuxaforEffectShutdownClass {
	GObjectClass parent_class;
};

struct _LuxaforEffectRandomColor {
	GObject parent_instance;
	LuxaforEffectRandomColorPrivate * priv;
};

struct _LuxaforEffectRandomColorClass {
	GObjectClass parent_class;
};


GQuark luxafor_error_quark (void);
gpointer luxafor_luxafor_ref (gpointer instance);
void luxafor_luxafor_unref (gpointer instance);
GParamSpec* luxafor_param_spec_luxafor (const gchar* name, const gchar* nick, const gchar* blurb, GType object_type, GParamFlags flags);
void luxafor_value_set_luxafor (GValue* value, gpointer v_object);
void luxafor_value_take_luxafor (GValue* value, gpointer v_object);
gpointer luxafor_value_get_luxafor (const GValue* value);
GType luxafor_luxafor_get_type (void) G_GNUC_CONST;
LuxaforLuxafor* luxafor_luxafor_new (libusb_context* context, GError** error);
LuxaforLuxafor* luxafor_luxafor_construct (GType object_type, libusb_context* context, GError** error);
void luxafor_luxafor_close (LuxaforLuxafor* self);
GQuark device_error_quark (void);
void luxafor_luxafor_write (LuxaforLuxafor* self, guint8* data, int data_length1, GError** error);
GQuark effect_error_quark (void);
GType luxafor_effect_effect_get_type (void) G_GNUC_CONST;
void luxafor_luxafor_send (LuxaforLuxafor* self, LuxaforEffectEffect* effect, GError** error);
GType luxafor_device_usb_device_finder_get_type (void) G_GNUC_CONST;
libusb_device* luxafor_device_usb_device_finder_find (LuxaforDeviceUsbDeviceFinder* self, GError** error);
GType luxafor_device_luxafor_finder_get_type (void) G_GNUC_CONST;
LuxaforDeviceLuxaforFinder* luxafor_device_luxafor_finder_new (libusb_context* context);
LuxaforDeviceLuxaforFinder* luxafor_device_luxafor_finder_construct (GType object_type, libusb_context* context);
void luxafor_effect_effect_handle (LuxaforEffectEffect* self, LuxaforLuxafor* luxafor, GError** error);
GType luxafor_effect_raw_get_type (void) G_GNUC_CONST;
LuxaforEffectRaw* luxafor_effect_raw_new (guint8* bytes, int bytes_length1);
LuxaforEffectRaw* luxafor_effect_raw_construct (GType object_type, guint8* bytes, int bytes_length1);
GType luxafor_effect_fade_to_get_type (void) G_GNUC_CONST;
GType luxafor_effect_color_get_type (void) G_GNUC_CONST;
LuxaforEffectFadeTo* luxafor_effect_fade_to_new (LuxaforEffectColor* color, guint8 speed);
LuxaforEffectFadeTo* luxafor_effect_fade_to_construct (GType object_type, LuxaforEffectColor* color, guint8 speed);
guint8 luxafor_effect_fade_to_get_speed (LuxaforEffectFadeTo* self);
void luxafor_effect_fade_to_set_speed (LuxaforEffectFadeTo* self, guint8 value);
LuxaforEffectColor* luxafor_effect_color_new (guint8 red, guint8 green, guint8 blue);
LuxaforEffectColor* luxafor_effect_color_construct (GType object_type, guint8 red, guint8 green, guint8 blue);
guint8 luxafor_effect_color_get_red (LuxaforEffectColor* self);
void luxafor_effect_color_set_red (LuxaforEffectColor* self, guint8 value);
guint8 luxafor_effect_color_get_green (LuxaforEffectColor* self);
void luxafor_effect_color_set_green (LuxaforEffectColor* self, guint8 value);
guint8 luxafor_effect_color_get_blue (LuxaforEffectColor* self);
void luxafor_effect_color_set_blue (LuxaforEffectColor* self, guint8 value);
GType luxafor_effect_shutdown_get_type (void) G_GNUC_CONST;
LuxaforEffectShutdown* luxafor_effect_shutdown_new (void);
LuxaforEffectShutdown* luxafor_effect_shutdown_construct (GType object_type);
GType luxafor_effect_random_color_get_type (void) G_GNUC_CONST;
LuxaforEffectRandomColor* luxafor_effect_random_color_new (void);
LuxaforEffectRandomColor* luxafor_effect_random_color_construct (GType object_type);


G_END_DECLS

#endif
